config/routes.rb
Rails.application.routes.draw do
  get 'offer_requests/new'
  post 'offer_requests/create'

  root 'offer_requests#new'

end

app/models/concerns/mobile_offer_api_url.rb
require 'active_support/concern'
require 'security_signature'
require 'net/http'

module MobileOfferApiUrl

  extend ActiveSupport::Concern

  APP_ID = 157
  FORMAT = 'json'
  DEVICE_ID = "2b6f0cc904d137be2e1730235f5664094b831186"
  LOCALE = 'de'
  IP = '109.235.143.113'
  OFFER_TYPES = 112
  VERSION = 'v1'

  def url
    "#{base_url}?#{params_url}"
  end

  private

  def base_url
    "http://api.sponsorpay.com/feed/#{VERSION}/offers.#{FORMAT}"
  end

  def params_url
    api_params = base_params.merge(dynamic_params)
    hashkey = SecuritySignature.sign(api_params)
    api_params.merge!({hashkey: hashkey})

    api_params.map { |k, v| "#{k}=#{v}" }.join('&')
  end

  def base_params
    {
      appid: APP_ID,
      ip: IP,
      locale: LOCALE,
      device_id: DEVICE_ID,
      offer_types: OFFER_TYPES,
    }
  end

  def dynamic_params
    {
      pub0: pub0,
      page: page,
      uid: uid,
      timestamp: DateTime.now.utc.to_i
    }.reject{ |key,value| value.blank? }
  end

end

app/models/offer.rb
class Offer
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :uid, :pub0, :page

  validates_presence_of :uid, :pub0, :page
  validates_numericality_of :page

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/offer_request.rb
require 'mobile_offer_api'

class OfferRequest
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  include MobileOfferApiUrl

  attr_accessor :uid, :pub0, :page

  validates_presence_of :uid, :pub0
  validates_numericality_of :page, allow_blank: true

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

  def offers_response
    MobileOfferApi.new(self).offers_response
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/offer_requests_controller.rb
class OfferRequestsController < ApplicationController
  def new
    @offer_request = OfferRequest.new
  end

  def create
    @offer_request = OfferRequest.new params[:offer_request]

    unless @offer_request.valid?
      flash.now[:alert] = 'Please fix the errors'
      render :new
      return
    end

    offers_response = @offer_request.offers_response

    if offers_response.has_errors
      flash.now[:alert] = offers_response.error_message
      render :new
      return
    end

    @offers = offers_response.offers
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sponsorpay</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="flash_messages">
  <% flash.each do |name, message| %>
    <%= content_tag(:div, message, :class => "flash #{name}") %>
  <% end %>
</div>

<%= yield %>

</body>
</html>

app/views/offer_requests/_error_messages.erb
<% if object && object.errors.any? %>
  <div id="error_explanation">
    <h3><%= "Please fix #{object.errors.size} #{object.class.to_s.underscore.humanize.downcase} errors" %></h3>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/offer_requests/_offer.html.erb
<li class="offers-list">
  <div class='offer'>
    <div class='title'><%= offer['title'] %></div>
    <div class='payout'><%= offer['payout'] %></div>
    <div class='thumbnail'><%= image_tag offer['thumbnail']['lowres'] %></div>
  </div>
</li>

app/views/offer_requests/create.html.erb
<% if @offers.blank? %>
  <div class='no_offers'>
    No offers
  </div>
<% else %>
  <h1>Received Offers:</h1>

  <ul>
    <% @offers.each do |offer| %>
      <%= render 'offer', offer: offer %>
    <% end %>
  </ul>
<% end %>

<%= link_to 'Make another offers request', root_path %>

app/views/offer_requests/new.html.erb
<h1>Get Offers</h1>
<%= form_for @offer_request, :url => offer_requests_create_path do |f| %>
  <%= render 'error_messages', object: f.object %>

  <fieldset>
    <%= f.text_field :uid, placeholder: 'uid' %>
    <%= f.text_field :pub0, placeholder: 'pub0' %>
    <%= f.text_field :page, placeholder: 'page' %>
  </fieldset>

  <%= f.submit 'Get Offers' %>

<% end %>

<%= link_to 'Make another offers request', root_path %>

app/views/offers/new.html.erb
<h1>Get Offers</h1>
<%= form_for @offer, :url => offers_create_path do |f| %>
  <%= render 'error_messages', object: f.object %>

  <fieldset>
    <%= f.text_field :uid, placeholder: 'uid' %>
    <%= f.text_field :pub0, placeholder: 'pub0' %>
    <%= f.text_field :page, placeholder: 'page' %>
  </fieldset>

  <%= f.submit 'Get Offers' %>

<% end %>